version: '3'
services:

 neo4j:
    container_name: neo4j
    image: bitnami/neo4j:latest
    
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
      
 server:
     depends_on:
     - neo4j
     
     container_name: server
     restart: always 
     
     build:
       context: .
       dockerfile: DockerFile
     
     image: config-server:latest
     
     volumes:
       - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
     
     network_mode: "host"
     
     ports:
       - 8080:8080  
volumes:
   spring-cloud-config-repo:     